set ANDROID_SYSTEM_NAME=Android
set ANDROID_SYSTEM_VERSION=1
set ANDROID_ABI=armeabi-v7a
set ANDROID_PLATFORM=android-21
set ANDROID_BUILD_TYPE=Debug
set ANDROID_NDK=/Users/vic/Library/Android/sdk/ndk/21.1.6352462
set ANDROID_TOOLCHAIN_FILE=/Users/vic/Library/Android/sdk/ndk/21.1.6352462/build/cmake/android.toolchain.cmake
set ANDROID_TOOLCHAIN=clang
 
cd ./build
/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake .. -G "Unix Makefiles" -DCMAKE_SYSTEM_NAME=$ANDROID_SYSTEM_NAME -DCMAKE_SYSTEM_VERSION=$ANDROID_SYSTEM_VERSION -DANDROID_ABI=$ANDROID_ABI -DANDROID_PLATFORM=$ANDROID_PLATFORM -DCMAKE_BUILD_TYPE=$ANDROID_BUILD_TYPE -DANDROID_NDK=$ANDROID_NDK -DCMAKE_TOOLCHAIN_FILE=$ANDROID_TOOLCHAIN_FILE -DANDROID_TOOLCHAIN=$ANDROID_TOOLCHAIN
